CORGI-591: Add automation to keep Brew / Corgi build tags in sync
RedHatProductSecurity/component-registry pull request #422
Opened 2023-04-27 17:45 UTC by juspence

@RedHatProductSecurity/corgi-devs Please review. This change is needed to keep the tags up-to-date on Corgi builds whenever they change in Brew. Having up-to-date tags ensures that manifests always represent the latest released content for some stream and are never stale.

I added tests for the Celery task, but I'm not sure about the logic. Is it enough to call slow_load_errata() when errata tags get added to some build? Or is there something else I need to do, so that relations are created and the build is correctly linked to the erratum's variant?

I'm also not sure how to correctly clean up the relations, whenever some build has an errata tag removed. If someone has an easy idea for a solution, I can handle that as part of this MR. I could also file a backlog ticket, or we could avoid doing this at all if we never want to delete the relations (but that doesn't seem right).

2023-04-27 19:52 UTC, mprpic commented on corgi/monitor/consumer.py
> +            )
Did you test that this works? The docs around Receivers aren't super clear (and the code is not super readable either) so it's not apparent to me whether a Container supports multiple Receivers over a single Link. My worry here would be that if it only supports one, you're essentially overwriting receivers in a single container until you reach the last one.

2023-04-27 19:57 UTC, juspence commented on corgi/monitor/consumer.py
> +            )
Not yet, but if the overall MR looks good, I'm definitely planning on deploying to stage and testing before I merge.

2023-04-27 20:00 UTC, mprpic commented on corgi/monitor/consumer.py
> +            )
You can probably test this locally using your own UMB certs (or using the app stage ones) to connect to UMB stage :wink:

2023-04-27 20:16 UTC, juspence commented on corgi/monitor/consumer.py
> +            )
I tried a while ago to set up my own certs, but hit some issues with RHEL CSB I think. And I think if I use the stage ones, it will end up interfering with the queues / messages that stage should be processing.

2023-04-28 05:32 UTC, jasinner requested changes
Calling slow_load_errata from the slow_update_brew_tags function is the correct approach to ensure that the builds have the correct product taxonomy. 

I think we should modify the slow_update_brew_tags as suggested. This might mean we also need to updating when we call slow_load_errata in the slow_fetch_brew_build job so that it's only called for release_errata tags.

2023-04-28 05:32 UTC, jasinner commented on tests/test_tasks.py
> +    with patch("corgi.tasks.brew.slow_load_errata.delay") as mock_load_errata:
nitpik: In other tests we're using the @patch decorator, perhaps you should use that to keep the test consistent? Or did you have a specific reason to use this context method to patch the task?

2023-04-28 05:32 UTC, jasinner commented on corgi/tasks/brew.py
> +        return f"Added tag {tag_added} or removed tag {tag_removed} for build {build_id}"
```suggestion
        if tag_added:
            return "empty tag, not adding"

        def add_if_not_existing(value: str, target: list[str]) -> tuple[list[str], bool]:
            if value not in target:
                target.append(value)
                return sorted(target), True
            return target, False


        build.meta_attr["tags"], tags_updated = add_if_not_existing(tag_added, build.meta_attr["tags"])

        # Check if it's an errata_tag
        errata_tag = ADVISORY_REGEX.match(tag_added)
        if not errata_tag:
            if tags_updated:
                build.save()
            return f"{tag_added} not an errata tag"

        errata_tag = errata_tag.group()
        build.meta_attr["errata_tags"], _ = add_if_not_existing(errata_tag, build.meta_attr["errata_tags"])

        # We might consider refactoring this code from brew collector to a common base package
        if len(errata_tag.split(":", maxsplit=1)[-1]) != 4:
            build.save()
            return f"{tag_aded} not a released errata tag"

        build.meta_attr["released_errata_tags"], released_updated = add_if_not_existing(errata_tag, build.meta_attr["released_errata_tags"])
        if release_updated:
            slow_load_erata.delay(released_errata_tag)

        # If we got this far either one of errata_tags or released_errata_tag meta_attr values needs to be saved
        build.save()
        return f"Added tag {tag_added} or removed tag {tag_removed} for build {build_id}"
```

2023-04-28 13:47 UTC, juspence commented on corgi/tasks/brew.py
> +        return f"Added tag {tag_added} or removed tag {tag_removed} for build {build_id}"
I'm not sure I understand this suggestion, but I think you're proposing:

1. Only add tags, never remove them
2. Only update errata_tags if the tag really is an erratum name
3. Only update released_errata_tags if the tag really is released
4. Only call .save() if something was actually added in 1-3 above
5. Only call slow_load_errata() / create relations for released errata, not all errata

Number 4 makes sense, but the existing code should handle this as far as I understand. We shouldn't get messages about added tags which are already present/ removed tags which are already gone. So we'll always need to call .save(), because at least meta_attr["tags"] will get updated every time.

You added a comment, ```# We might consider refactoring this code from brew collector to a common base package```. But the custom code you added is already part of a separate method that we're reusing. Brew.extract_advisory_ids() and Brew.parse_advisory_ids() are the same methods we use during ingestion to set the errata_tags and released_errata_tags, respectively.

If the tag we added (or removed) isn't an erratum name or isn't released, the list of errata_tags and released_errata_tags won't change, respectively. So calling these methods might be a no-op, and they handle checking the tag format for us. I don't think having separate code to check "is this tag an erratum name?" is really needed in this task. AKA numbers 2 and 3 are handled - the methods we reuse are fairly lightweight no-ops in this case.

Number 5 makes sense, but doesn't match what we do during ingestion. We create relations for all errata, not just the released errata. I'm not sure where else we rely on the ERRATA-type relations, or what the impact would be if only released errata had relations created instead of all errata. Could this cause problems for Incident Response? I assume that when they filter by a particular variant, they want to see components / builds that aren't released yet but which are planned to be released in that variant.

I'm happy to make the change in both this task and the ingestion logic, but maybe we need a discussion about when we want to relate components to variants (at release time or at build time). For now only the manifests filter on "released components" and exclude unreleased components.

I don't really understand number 1 (don't remove tags) - can you clarify a bit? Or we can discuss on a call if you'd prefer.

2023-04-28 14:01 UTC, juspence commented on tests/test_tasks.py
> +    with patch("corgi.tasks.brew.slow_load_errata.delay") as mock_load_errata:
I like the context manager because it makes it clear which mock is patching which call. This makes longer tests more readable, and avoids issues where you might want to patch some calls but not others. For example, some of the UMB monitor tests have more-complex patching needs.

2023-05-01 13:56 UTC, juspence commented on corgi/monitor/consumer.py
> +            )
I see this is working after deploying to stage temporarily for testing. Splunk logs indicate that we're receiving, handling, and logging messages from multiple topics. I can't put the internal Splunk search link on this public discussion page, but you can search for "Handling UMB" to see the different brew.build.complete and brew.build.tag messages we're processing.

2023-05-01 14:15 UTC, juspence commented on corgi/tasks/brew.py
> +        return f"Added tag {tag_added} or removed tag {tag_removed} for build {build_id}"
@jasinner After thiking about it, number 1 above (don't remove tags) doesn't seem like the correct behavior, and number 5 (create relations for only released errata, instead of all errata) seems outside the scope of this ticket. 2 - 4 are already handled by the current code.

I've tested and confirmed multiple receivers / topics per handler works, so I've filed CORGI-618 as a followup ticket to handle number 5, and I'm going to merge the rest as-is. Let's please discuss if you have any concerns.

2023-05-01 19:43 UTC, jasinner approved these changes

2023-05-01 19:43 UTC, merged